# Generated by Django 4.1.6 on 2023-02-20 01:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('senha', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now=True)),
                ('is_instagram_admin', models.IntegerField(max_length=11)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.RenameModel(
            old_name='Main',
            new_name='Publicacoes',
        ),
    ]
