# Generated by Django 4.1.6 on 2023-02-20 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_alter_usuarios_is_instagram_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
